all:
  hosts:
    web01:
      ansible_host: 172.31.89.143
    web02:
      ansible_host: 172.31.95.190
    web03:
      ansible_host: 172.31.81.166
      ansible_user: ubuntu
    db01:
      ansible_host: 172.31.94.19

  children:
    webserver:
      hosts:
        web01:
        web02:
        web03:

    dbserver:
      hosts:
        db01:

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: server-key.pem