all:
  hosts:
    web01:
      ansible_host: <Add-IP>
    web02:
      ansible_host: <Add-IP>
    web03:
      ansible_host: <Add-IP>
      ansible_user: ubuntu
    db01:
      ansible_host: <Add-IP>

  children:
    webserver:
      hosts:
        web01:
        web02:
        web03:

    dbserver:
      hosts:
        db01:

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: server-key.pem
